backend:
  name: github
  repo: threshold-network/splash-page
  site_domain: threshold.network
  open_authoring: true

local_backend: true

site_url: https://threshold.network

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: pages
    label: "Pages"
    files:
      - file: "src/content/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Path", name: "path", widget: "hidden", default: "/" }
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  minimal: true,
                }
              - {
                  label: "Body",
                  name: "body",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "CTA Buttons",
                  name: "ctaButtons",
                  widget: "list",
                  allow_add: true,
                  required: false,
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      { label: URL, name: url, widget: string },
                    ],
                }
          - label: "Staker Role"
            name: "stakerRole"
            widget: "object"
            fields:
              - {
                  label: "Row Reverse",
                  name: "rowReverse",
                  widget: boolean,
                  required: false,
                  default: false,
                }
              - {
                  label: "Background Color",
                  name: "bgColor",
                  widget: color,
                  picker: block,
                  presetColors:
                    [
                      "#D6D6D6",
                      "#323232",
                      "#A3A3A3",
                      "#858585",
                      "#3C3C3C",
                      "#333333",
                      "#141414",
                    ],
                }
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  minimal: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: file,
                  media_library: { config: { multiple: false } },
                }
              - {
                  label: "Buttons",
                  name: "buttons",
                  widget: "list",
                  allow_add: true,
                  required: false,
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      { label: URL, name: url, widget: string },
                      {
                        label: Variant,
                        name: variant,
                        widget: select,
                        required: true,
                        options:
                          [
                            {
                              label: "External Solid",
                              value: "EXTERNAL_SOLID",
                            },
                            {
                              label: "Internal Solid",
                              value: "INTERNAL_SOLID",
                            },
                            {
                              label: "External Outline",
                              value: "EXTERNAL_OUTLINE",
                            },
                            {
                              label: "Internal Outline",
                              value: "INTERNAL_OUTLINE",
                            },
                          ],
                      },
                    ],
                }

          - label: "Liquidity Provider Role"
            name: "lpRole"
            widget: "object"
            fields:
              - {
                  label: "Row Reverse",
                  name: "rowReverse",
                  widget: boolean,
                  required: false,
                  default: false,
                }
              - {
                  label: "Background Color",
                  name: "bgColor",
                  widget: color,
                  picker: block,
                  presetColors:
                    [
                      "#D6D6D6",
                      "#323232",
                      "#A3A3A3",
                      "#858585",
                      "#3C3C3C",
                      "#333333",
                      "#141414",
                    ],
                }
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  minimal: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: file,
                  media_library: { config: { multiple: false } },
                }
              - {
                  label: "Buttons",
                  name: "buttons",
                  widget: "list",
                  allow_add: true,
                  required: false,
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      { label: URL, name: url, widget: string },
                      {
                        label: Variant,
                        name: variant,
                        widget: select,
                        required: true,
                        options:
                          [
                            {
                              label: "External Solid",
                              value: "EXTERNAL_SOLID",
                            },
                            {
                              label: "Internal Solid",
                              value: "INTERNAL_SOLID",
                            },
                            {
                              label: "External Outline",
                              value: "EXTERNAL_OUTLINE",
                            },
                            {
                              label: "Internal Outline",
                              value: "INTERNAL_OUTLINE",
                            },
                          ],
                      },
                    ],
                }
          - label: "Bitcoin User Role"
            name: "btcRole"
            widget: "object"
            fields:
              - {
                  label: "Row Reverse",
                  name: "rowReverse",
                  widget: boolean,
                  required: false,
                  default: false,
                }
              - {
                  label: "Background Color",
                  name: "bgColor",
                  widget: color,
                  picker: block,
                  presetColors:
                    [
                      "#D6D6D6",
                      "#323232",
                      "#A3A3A3",
                      "#858585",
                      "#3C3C3C",
                      "#333333",
                      "#141414",
                    ],
                }
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  minimal: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: file,
                  media_library: { config: { multiple: false } },
                }
              - {
                  label: "Buttons",
                  name: "buttons",
                  widget: "list",
                  allow_add: true,
                  required: false,
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      { label: URL, name: url, widget: string },
                      {
                        label: Variant,
                        name: variant,
                        widget: select,
                        required: true,
                        options:
                          [
                            {
                              label: "External Solid",
                              value: "EXTERNAL_SOLID",
                            },
                            {
                              label: "Internal Solid",
                              value: "INTERNAL_SOLID",
                            },
                            {
                              label: "External Outline",
                              value: "EXTERNAL_OUTLINE",
                            },
                            {
                              label: "Internal Outline",
                              value: "INTERNAL_OUTLINE",
                            },
                          ],
                      },
                    ],
                }
          - label: "Token Holder Role"
            name: "tokenHolderRole"
            widget: "object"
            fields:
              - {
                  label: "Row Reverse",
                  name: "rowReverse",
                  widget: boolean,
                  required: false,
                  default: false,
                }
              - {
                  label: "Background Color",
                  name: "bgColor",
                  widget: color,
                  picker: block,
                  presetColors:
                    [
                      "#D6D6D6",
                      "#323232",
                      "#A3A3A3",
                      "#858585",
                      "#3C3C3C",
                      "#333333",
                      "#141414",
                    ],
                }
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  minimal: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: file,
                  media_library: { config: { multiple: false } },
                }
              - {
                  label: "Buttons",
                  name: "buttons",
                  widget: "list",
                  allow_add: true,
                  required: false,
                  fields:
                    [
                      { label: Label, name: label, widget: string },
                      { label: URL, name: url, widget: string },
                      {
                        label: Variant,
                        name: variant,
                        widget: select,
                        required: true,
                        options:
                          [
                            {
                              label: "External Solid",
                              value: "EXTERNAL_SOLID",
                            },
                            {
                              label: "Internal Solid",
                              value: "INTERNAL_SOLID",
                            },
                            {
                              label: "External Outline",
                              value: "EXTERNAL_OUTLINE",
                            },
                            {
                              label: "Internal Outline",
                              value: "INTERNAL_OUTLINE",
                            },
                          ],
                      },
                    ],
                }
  - name: "components"
    label: "Components"
    files:
      - file: "src/content/components/take-the-quiz-banner.md"
        label: "Take the quiz banner"
        name: "takeTheQuizBanner"
        fields:
          - {
              label: "Template Key",
              name: "template",
              widget: "hidden",
              default: "take-the-quiz-banner",
            }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: true,
            }
          - {
              label: "Button Text",
              name: "buttonText",
              widget: "string",
              required: true,
            }
      - file: "src/content/components/announcement-banner.md"
        label: "Announcement Banner"
        name: "announcement"
        fields:
          - {
              label: "Template Key",
              name: "template",
              widget: "hidden",
              default: "announcement",
            }
          - { label: "Title", name: "title", widget: "string", required: false }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              required: true,
              minimal: true,
            }
      - file: "src/content/components/nav-bar.md"
        label: "Navigation Bar"
        name: "nav"
        fields:
          - {
              label: "Template Key",
              name: "template",
              widget: "hidden",
              default: "nav-bar",
            }
          - {
              label: "Nav Items",
              name: "nav_items",
              widget: "list",
              allow_add: true,
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  {
                    label: "URL",
                    name: "url",
                    widget: "string",
                    required: false,
                    hint: "Use a relative URL (e.g. /press) if the link is an internal link.",
                  },
                  {
                    label: "External Link",
                    name: "isExternal",
                    widget: "boolean",
                    required: false,
                    default: false,
                  },
                  {
                    label: "Sub Items",
                    name: "subitems",
                    widget: "list",
                    allow_add: true,
                    fields:
                      [
                        { label: "Label", name: "label", widget: "string" },
                        {
                          label: "External Link",
                          name: "isExternal",
                          widget: "boolean",
                          default: false,
                          required: false,
                        },
                        {
                          label: "URL",
                          name: "url",
                          widget: "string",
                          hint: "Use a relative URL (e.g. /press) if the link is an internal link.",
                        },
                      ],
                  },
                ],
            }
          - {
              label: "Social Media Links",
              name: "social_links",
              widget: "list",
              allow_add: true,
              fields:
                [
                  {
                    label: "Label",
                    name: "label",
                    widget: "string",
                    required: false,
                  },
                  { label: "URL", name: "url", widget: "string" },
                  {
                    label: Icon,
                    name: icon,
                    widget: object,
                    fields:
                      [
                        {
                          label: "Image",
                          name: "image",
                          widget: file,
                          required: true,
                          media_library: { config: { multiple: false } },
                          hint: "SVG only. SVG must have width and height attributes set in the file.",
                        },
                        { label: "Alt", name: "alt", widget: "string" },
                      ],
                  },
                ],
            }
